name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git \
          openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libffi-dev
          pip3 install buildozer cython
      - name: Accept Android SDK licenses
        run: |
          yes | buildozer android debug || true
      - name: Build APK
        run: buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
